"""Add mercado_pago_id and status to Donation

Revision ID: 71de91ed424a
Revises: abe1c24acd22
Create Date: 2025-06-26 00:18:22.518663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71de91ed424a'
down_revision = 'abe1c24acd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        # Adiciona as colunas, permitindo nulos temporariamente para não falhar em tabelas com dados
        batch_op.add_column(sa.Column('mercado_pago_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        # Adiciona a restrição de unicidade para o ID do Mercado Pago
        batch_op.create_unique_constraint('uq_donations_mercado_pago_id', ['mercado_pago_id'])

    # Atualiza as linhas existentes para que a coluna 'status' não seja nula
    op.execute("UPDATE donations SET status = 'approved' WHERE status IS NULL")

    # Altera a coluna 'status' para ser NOT NULL, como planejado originalmente
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=50), nullable=False)

    # A parte que mexia com a tabela 'users' foi REMOVIDA para evitar o erro de duplicidade.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_donations_mercado_pago_id', type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('mercado_pago_id')

    # A parte que mexia com a tabela 'users' também foi removida da função de downgrade.
    # ### end Alembic commands ###